name: Syncer

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    name: Automatic sync
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git grep
    - name: Sync
      run: |
        git config --global user.name "${GIT_USERNAME}"
        git config --global user.email "${GIT_EMAIL}"
        git clone https://github.com/ACL4SSR/ACL4SSR.git -b master
        cd ACL4SSR
        grep https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master -rl | xargs -i sed -i s#https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master#https://gitea.com/zclkkk/ACL4SSR/raw/branch/master#g {}
        git commit -a -m "Switch to our mirror"
        git push -f  https://${GIT_USERNAME}:${GIT_PASSWORD}@gitea.com/${GIT_USERNAME}/ACL4SSR.git 
      env:
        GIT_EMAIL: 2484392714@qq.com
        GIT_PASSWORD: ${{ secrets.PASSWORD }}
        GIT_USERNAME: zclkkk
